name: Deploy to Dev

on:
  push:
    branches: [ develop ]
  workflow_dispatch:
    inputs:
      skip_tests:
        description: 'Skip tests before deployment'
        required: false
        default: 'false'

jobs:
  deploy:
    name: Deploy to Development Instance
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        if: ${{ github.event.inputs.skip_tests != 'true' }}
        run: npm run test

      - name: Configure ServiceNow credentials
        run: |
          echo "SN_INSTANCE=${{ secrets.SN_DEV_INSTANCE }}" >> $GITHUB_ENV
          echo "SN_USERNAME=${{ secrets.SN_DEV_USERNAME }}" >> $GITHUB_ENV
          echo "SN_PASSWORD=${{ secrets.SN_DEV_PASSWORD }}" >> $GITHUB_ENV

      - name: Deploy tables
        run: npm run sync:tables

      - name: Deploy server code
        run: npm run sync:server

      - name: Deploy client code
        run: npm run sync:client

      - name: Deployment summary
        run: |
          echo "Deployment completed successfully!"
          echo "Instance: ${{ secrets.SN_DEV_INSTANCE }}"
          echo "Scope: x_902080_msmplnpkr_fluent"
          echo "Timestamp: $(date)"
